import type { Express, Request, Response } from 'express';
import type { PushService } from './service';

const FIREBASE_WEB_SDK_VERSION = '12.17.1';
const FIREBASE_PROJECT_ID = 'microprojects-481213';
const FIREBASE_APP_ID = '1:917911030888:web:c474b419d5a03c0066bfdd';
const FIREBASE_SENDER_ID = '917911030888';
const FIREBASE_AUTH_DOMAIN = 'microprojects-481213.firebaseapp.com';

function asyncRoute(handler: (req: Request, res: Response) => Promise<void>) {
  return (req: Request, res: Response) => {
    handler(req, res).catch((error: any) => {
      console.error(error);
      res.status(500).json({ error: error?.message || 'Push notification request failed' });
    });
  };
}

function serviceWorkerSource(apiKey: string) {
  const firebaseConfig = JSON.stringify({
    apiKey,
    authDomain: FIREBASE_AUTH_DOMAIN,
    projectId: FIREBASE_PROJECT_ID,
    messagingSenderId: FIREBASE_SENDER_ID,
    appId: FIREBASE_APP_ID
  });
  return `/* Generated by Spararama. Do not edit in the browser. */
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_WEB_SDK_VERSION}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_WEB_SDK_VERSION}/firebase-messaging-compat.js');

firebase.initializeApp(${firebaseConfig});
const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const title = data.title || 'Spararama';
  const options = {
    body: data.body || '',
    tag: data.notificationId ? 'spararama-' + data.notificationId : 'spararama-heating',
    renotify: Boolean(data.requiresConfirmation === 'true'),
    requireInteraction: Boolean(data.requiresConfirmation === 'true'),
    data: {
      url: data.url || '/',
      scheduleId: data.scheduleId,
      notificationId: data.notificationId,
      kind: data.kind
    }
  };
  return self.registration.showNotification(title, options);
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const destination = new URL(event.notification.data?.url || '/', self.location.origin).href;
  event.waitUntil((async () => {
    const windows = await clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of windows) {
      if ('focus' in client) {
        if ('navigate' in client) await client.navigate(destination);
        return client.focus();
      }
    }
    return clients.openWindow(destination);
  })());
});
`;
}

export function registerPushRoutes(app: Express, push: PushService) {
  app.get('/api/push/config', asyncRoute(async (_req, res) => {
    const status = await push.status();
    const browserApiKeyConfigured = Boolean(String(process.env.VITE_FIREBASE_API_KEY || '').trim());
    res.json({ ...status, browserApiKeyConfigured, configured: status.configured && browserApiKeyConfigured });
  }));

  app.post('/api/push/registrations', asyncRoute(async (req, res) => {
    const token = typeof req.body?.token === 'string' ? req.body.token : '';
    const registration = await push.register({
      token,
      userAgent: typeof req.body?.userAgent === 'string' ? req.body.userAgent.slice(0, 500) : undefined,
      label: typeof req.body?.label === 'string' ? req.body.label.slice(0, 120) : undefined
    });
    res.status(201).json({ id: registration.id, createdAt: registration.createdAt, updatedAt: registration.updatedAt });
  }));

  app.delete('/api/push/registrations/:id', asyncRoute(async (req, res) => {
    res.json({ removed: await push.unregister(req.params.id) });
  }));

  app.post('/api/push/test', asyncRoute(async (_req, res) => {
    const now = Date.now();
    const result = await push.sendHeatingNotification({
      id: `push-test-${now}`,
      scheduleId: 'push-test',
      kind: 'heater_started',
      createdAt: now,
      title: 'Spararama notifications enabled',
      message: 'Background push notifications are working on this device.',
      requiresConfirmation: false
    });
    res.json(result);
  }));

  app.get('/firebase-messaging-sw.js', (_req, res) => {
    res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
    res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
    res.setHeader('Service-Worker-Allowed', '/');
    res.send(serviceWorkerSource(String(process.env.VITE_FIREBASE_API_KEY || '').trim()));
  });
}
